apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hello-happy-birthday
  spec:
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPrecentage: 50
    scaleTargetRef:
      apiVersion: extensions/v1beta1
      kind: Deployment
      name: hello-happy-birthday