apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-happy-birthday
  labels:
    app: hello-happy-birthday
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-happy-birthday
    spec:
      containers:
        - name: hello-happy-birthday
          image: 'docker.io/dozza/spring-boot-pg:latest'
          ports:
            - containerPort: 8080
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: csql-secrets
                  key: username
            - name: DB_PASS
              valueFrom:
                  secretKeyRef:
                    name: csql-secrets
                    key: password
            - name: DB_NAME
              valueFrom:
                  secretKeyRef:
                    name: csql-secrets
                    key: dbname
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy
            # Change <INSTANCE_CONNECTION_NAME> here to include your GCP
          # project, the region of your Cloud SQL instance and the name
          # of your Cloud SQL instance. The format is $PROJECT:$REGION:$INSTANCE
          command: ["/cloud-sql-proxy",
                    "-instances=<INSTANCE_CONNECTION_NAME>=tcp:5432",
                    "-credentials_file=/secrets/cloudsql/account.json"]
          volumeMounts:
            - name: my-secrets-volume
              mountPath: /secrets/cloudsql
              readOnly: true
    volumes:
      - name: my-secrets-volume
        secret:
          secretName: cloudsql-instance-credentials