apiVersion: extensions/v1beta1
kind: Service
metadata:
  name: hello-happy-birthday
  labels:
    app: hello-happy-birthday
spec:
  type: LoadBalancer
  selector:
    app: hello-happy-birthday
  ports:
    - protocol: TCP
      port: 80