apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-revolut
spec:
  selector:
    matchLabels:
      app: hello-revolut
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-revolut
    spec:
      containers:
        - name: hello-revolut
          image: dozza/spring-boot-pg:latest
