apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-revolut
spec:
  selector:
    matchLabels:
      app: hello-revolut
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-revolut
    spec:
      containers:
        - name: hello-revolut
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_password
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: hostname-config
                  key: postgres_host

          image: dozza/spring-boot-pg:latest
